services:
  web:
    build:
      context: ./apps/web
    ports:
      - "80:5173"
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: [ "pnpm", "run", "dev", "--host" ]

volumes:
  web_node_modules:
